DROP TABLE IF EXISTS conversations CASCADE;
CREATE TABLE conversations (
  id SERIAL PRIMARY KEY NOT NULL,
  sender_id INTEGER REFERENCES users(id) NOT NULL ON DELETE CASCADE,
  receiver_id INTEGER REFERENCES users(id) NOT NULL ON DELETE CASCADE,
  item_id INTEGER REFERENCES items(id) NOT NULL ON DELETE CASCADE
);
